language: cpp
compiler: gcc

os: linux
dist: xenial

install:
  - sudo apt update
  - sudo apt install libgtest-dev
  - (cd /usr/src/gtest && sudo `which cmake` .)
  - sudo make -C /usr/src/gtest
  - sudo ln -s /usr/src/gtest/libgtest.a /usr/lib/libgtest.a
  - sudo ln -s /usr/src/gtest/libgtest_main.a /usr/lib/libgtest_main.a
  - wget https://www.openssl.org/source/openssl-1.1.0f.tar.gz
  - tar xzvf openssl-1.1.0f.tar.gz
  - cd openssl-1.1.0f
  - ./config -Wl,--enable-new-dtags,-rpath,'$(LIBRPATH)'
  - make
  - sudo make install

script:
  - cmake .
  - make
  - ./jwt-cpp-test
