language: cpp
compiler: gcc

os: linux
dist: xenial

install:
  - sudo apt update
  - sudo apt install libgtest-dev
  - (cd /usr/src/gtest && sudo `which cmake` .)
  - sudo make -C /usr/src/gtest
  - sudo make -C /usr/src/gtest install
  - wget -O /tmp/openssl-1.1.0f.tar.gz https://www.openssl.org/source/openssl-1.1.0f.tar.gz
  - tar -xzvf /tmp/openssl-1.1.0f.tar.gz -C /tmp
  - (cd /tmp/openssl-1.1.0f && ./config -Wl,--enable-new-dtags,-rpath,'$(LIBRPATH)')
  - make -C /tmp/openssl-1.1.0f
  - sudo make -C /tmp/openssl-1.1.0f install

script:
  - cmake .
  - make
  - ./jwt-cpp-test
